CREATE TABLE  "ORGANIZATION"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(255) NOT NULL ENABLE,
	"REGISTRATION_ID" NUMBER NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(4000) NOT NULL ENABLE,
	"PHONE_NUMBER" VARCHAR2(255),
	"EMAIL" VARCHAR2(255),
	"CREATOR_ID" NUMBER,
	"CREATED_BY" VARCHAR2(100) NOT NULL ENABLE,
	"CREATED_ON" DATE NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(100) NOT NULL ENABLE,
	"UPDATED_ON" DATE NOT NULL ENABLE,
	"TAGS" VARCHAR2(1024),
	"LOGO_BLOB" BLOB,
	"LOGO_MIME" VARCHAR2(100),
	"LOGO_FILENAME" VARCHAR2(100),
	 CONSTRAINT "ORGANIZATION_PK" PRIMARY KEY ("ID") ENABLE
   ) ;

-- not in use -- CREATE SEQUENCE   "ORGANIZATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ; -- not in use --

CREATE OR REPLACE TRIGGER  "ORGANIZATION_BIU"
 before insert or update on "ORGANIZATION"
 for each row
begin
 if :NEW."ID" is null then
       :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
 end if;
   if inserting then
       :new.created_by := lower(nvl(v('APP_USER'),user));
       :new.created_on := sysdate;
   end if;
   :new.updated_by := lower(nvl(v('APP_USER'),user));
   :new.updated_on := sysdate;
end;

/
ALTER TRIGGER  "ORGANIZATION_BIU" ENABLE;
